### ISSUE TITLE
Script not portable to macOS due to sed regex

### ISSUE THREAD

**Issue by mrolli** [ansible-buch/init-ansible-project#1]
Me and many other developers use macOS based development environments. macOS comes with BSD `sed` and not GNU `sed` that are not 100% compatible. This is especially true when it comes to regular expression support. The script in its current form works on GNU `sed` but fails with BSD `sed`. Using the latter, the generated files `ansible.cfg`, `.envrc` and `inventory` are created but with zero bytes as the `sed` command on [this line](https://github.com/ansible-buch/init-ansible-project/blob/9a9a316dd75b514644e8fe6c7251c5087aa7407f/init-ansible-project.sh#L28)) fails due to the lack of ehanced feature in BSD `sed`.

I will ship a PR with the simple change, that makes the script compatible with `sed` on macOS.

See [here](https://stackoverflow.com/questions/12178924/os-x-sed-e-doesnt-accept-extended-regular-expressions) for further details about the issue.

**Comment by ansible-buch** [comment]
Thank you very much for your contribution!
